debug step added

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -44,6 +44,22 @@ jobs:
           echo "PAYLOAD_SECRET_KEY: $PAYLOAD_SECRET_KEY"
           echo "DATABASE_URI: $DATABASE_URI"
 
+          # Check if variables are empty
+          if [ -z "$NODE_ENV" ]; then
+            echo "ERROR: NODE_ENV is not set!"
+            exit 1
+          fi
+
+          if [ -z "$PAYLOAD_SECRET_KEY" ]; then
+            echo "ERROR: PAYLOAD_SECRET_KEY is not set!"
+            exit 1
+          fi
+
+          if [ -z "$DATABASE_URI" ]; then
+            echo "ERROR: DATABASE_URI is not set!"
+            exit 1
+          fi
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
